version: "3"
services:
  app:
    container_name: "go-production-boilerplate"
    env_file: "./app/.env"
    build:
        context: "./app"
        dockerfile: "Dockerfile.prod"
    command: ./go-production-boilerplate
    ports:
      - "8085:80"
    volumes:
      - ./app/log:/go/src/app/log
  nginx:
    container_name: "nginx"
    build:
      context: "./nginx"
      dockerfile: "Dockerfile.prod"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "app"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
