version: "3"
services:
  app:
    container_name: "go-production-boilerplate"
    env_file: "./app/.env"
    build:
        context: "./app"
        dockerfile: "Dockerfile"
    command: realize start --run
    ports:
      - "8085:8085"
    volumes:
      - ./app:/go/src/github.com/bmf-san/go-production-boilerplate/app
  nginx:
    container_name: "nginx"
    build:
        context: "./nginx"
        dockerfile: "Dockerfile"
    ports:
      - "80:80"
    depends_on:
      - "app"
